# Workflow for testing multiple bash versions with Docker
name: bash

on: [pull_request]

jobs:
  bash-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bash-version:
          - '3.2'
          - '4.2'
          # if you use a value like 5.0, YAML will round it to 5, which will cause an error later on
          - '5.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker container
        run: |
          docker build -t bash:test  -m 1G --memory-swap 1G dockerfiles/bash/
          docker run --name bash -v $(pwd -P):/root/cylc-flow --rm -t -d -m 1G --memory-swap 1G bash:test /bin/bash
          docker ps -a

      - name: Install Cylc dependencies in the container
        run: |
          docker exec bash python3.7 -m pip install six==1.12
          docker exec -w /root/cylc-flow bash python3.7 -m pip install .[all]

      - name: Set the container bash version
        run: docker exec bash update-alternatives --set bash /bash/bash-${{ matrix.bash-version }}

      - name: Run functional tests that validate or are related to how Cylc uses bash
        run: |
          docker exec -w /root/cylc-flow bash \
            ./etc/bin/run-functional-tests -v \
            tests/functional/broadcast/00-simple.t \

      - name: Copy cylc-run out of container
        if: failure()
        run: |
          docker cp bash:/root/cylc-run .

      - name: Upload
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Upload cylc-run artifact
          path: cylc-run
